# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run test

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run bot
      env:
        USER_AGENT: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0'
        API_KEY: ${{ secrets.API_KEY }}
        API_SECRET: ${{ secrets.API_SECRET }}
        BOT_KEY: ${{ secrets.BOT_KEY }}
        GROUP_KEY: ${{ secrets.GROUP_KEY }}
      run: |
        python3 ./bot.py
        
    - name: Commit files
      id: commit
      run: |
        if [-z "$(git status --porcelain)"]; then
            git config --local user.email ${{ secrets.GITH_EMAIL }}
            git config --local user.name "0peters"
            git add --all
            if [-z "$(git status --porcelain)"]; then
               echo "::set-output name=push::false"
            else
               git commit -m "Add changes" -a
               echo "::set-output name=push::true"
            fi
         fi
      shell: bash
    - name: Push changes
      if: steps.commit.outputs.push == 'true'
      uses: ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.GITH_TOKEN }}
